---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecothon
spec:
  replicas: 2
  selector:
    matchLabels:
      name: ecothon
  template:
    metadata:
      labels:
        name: ecothon
    spec:
      containers:
      - name: application
        image: georgehoneywood/ecothon
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env: 
        - name: ECOTHON_DB_PASS
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ECOTHON_DB_PASS
        - name: ECOTHON_SPACES_KEY
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ECOTHON_SPACES_KEY
        - name: ECOTHON_SPACES_SECRET
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: ECOTHON_SPACES_SECRET