name: Custom deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build

    - name: copy build artifacts to deploy
      uses: appleboy/scp-action@master
      with:
        host: git.honefox.uk
        username: ecothon
        key: ${{ secrets.SSH_KEY }}
        source: "ecothon, static/"
        target: "~/"
