name: Deploy to VPS (ecothon.space)

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    
    - uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
          ~/Library/Caches/go-build
          %LocalAppData%\go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: go build it
      run: go build
    
    # - name: list files
    #   run: ls -lahR

    - name: Copy build artifacts to VPS
      uses: appleboy/scp-action@master
      with:
        host: ecothon.space
        username: ecothon
        key: ${{ secrets.SSH_KEY }}
        source: "backend/ecothon, backend/static/"
        target: "~/"
        
    - name: Restart ecothon server
      uses: appleboy/ssh-action@master
      with:
        host: ecothon.space
        username: ecothon
        key: ${{ secrets.SSH_KEY }}
        script: |
          mv static static.bak
          mv backend/* .
          sudo /bin/systemctl restart ecothon
          rm -r static.bak/ backend/
