name: deploy to vps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - uses: actions/checkout@v2

    - name: set up go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: go build it
      run: go build
    
    - name: list files
      run: ls -lahR

    - name: copy build artifacts to deploy
      uses: appleboy/scp-action@master
      with:
        host: git.honeyfox.uk
        username: ecothon
        key: ${{ secrets.SSH_KEY }}
        source: "backend/ecothon, backend/static/"
        target: "~/"
        
    - name: restart ecothon server
      uses: appleboy/ssh-action@master
      with:
        host: git.honeyfox.uk
        username: ecothon
        key: ${{ secrets.SSH_KEY }}
        script: |
          mv static static.bak
          mv backend/* .
          ls -alh
          sudo /bin/systemctl restart ecothon
          rm -r static.bak
